SUGGESTION_STATE_NOT_CHECKED = 'NOT CHECKED'
SUGGESTION_STATE_CHECKING = 'CHECKING'
SUGGESTION_STATE_CHECKED = 'CHECKED'

SUGGESTION_STATES = (
    (SUGGESTION_STATE_NOT_CHECKED, 'بررسی نشده'),
    (SUGGESTION_STATE_CHECKING, 'در حال بررسی'),
    (SUGGESTION_STATE_CHECKED, 'بررسی شده'),
)
