SUGGESTION_STATE_NOT_CHECKED = 'NOT CHECKED'
SUGGESTION_STATE_CHECKING = 'CHECKING'
SUGGESTION_STATE_CHECKED = 'CHECKED'

SUGGESTION_STATES = (
    SUGGESTION_STATE_NOT_CHECKED,
    SUGGESTION_STATE_CHECKING,
    SUGGESTION_STATE_CHECKED,
)

DEPARTMENT_EDUCATION = 'EDUCATION'
DEPARTMENT_SERVICE = 'SERVICE'

RELATED_DEPARTMENTS = (
    DEPARTMENT_SERVICE,
    DEPARTMENT_EDUCATION
)
