# Generated by Django 4.1.5 on 2023-01-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('username', models.CharField(max_length=50, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=50, verbose_name='گذرواژه')),
                ('phone_number', models.CharField(max_length=50, verbose_name='شماره موبایل')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suggestions.user')),
                ('student_number', models.CharField(max_length=12, verbose_name='شماره دانشجویی')),
            ],
            bases=('suggestions.user',),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('suggestion_text', models.TextField(verbose_name='متن پیشنهاد')),
                ('submission_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت پیشنهاد')),
                ('related_department', models.CharField(max_length=200, verbose_name='بخش مربوطه')),
                ('state', models.CharField(choices=[('NOT CHECKED', 'بررسی نشده'), ('CHECKING', 'در حال بررسی'), ('CHECKED', 'بررسی شده')], max_length=50, verbose_name='وضعیت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='suggestions.student', verbose_name='دانشجوی ثبت کننده پیشنهاد')),
            ],
        ),
    ]
